---
title: "deliverable-1"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Loading packages

```{r, include=FALSE}
# Load Required Packages: to be increased over the course
library(car)  # Manual way, use for Boxplot()

requiredPackages <- c("car","knitr","FactoMineR","missMDA","mvoutlier","chemometrics")
missingPackages <- requiredPackages[!(requiredPackages %in% installed.packages()[,"Package"])]

if(length(missingPackages)) install.packages(missingPackages)
lapply(requiredPackages, require, character.only = TRUE)
install.packages("missMDA",dependencies = TRUE)

```


# Loading data


```{r}

setwd("C:/Users/Sergio/Dropbox/UPC/FIB/Analisis de datos y explotacion de la informacion (ADEI)/Proyecto/")

load("set-datos.RData", envir = parent.frame(), verbose = FALSE)

#Comprobar el tamaño de la muestra
nrow(df)
ncol(df)
dim(df)
```

# Exploratory Data Analysis

```{r}
# Graphics
names(df)
# Overview of data frame 
summary(df)

# List with names of target variables
vars_target<-names(df)[c(11,21)];vars_target

summary(df[,vars_target])
hist(df$duration,100)
boxplot(df$duration)

# Some useful functions
calcQ <- function(x) {
  s.x <- summary(x)
  iqr<-s.x[5]-s.x[2]
  list(souti=s.x[2]-3*iqr, mouti=s.x[2]-1.5*iqr, min=s.x[1], q1=s.x[2], q2=s.x[3], 
       q3=s.x[5], max=s.x[6], mouts=s.x[5]+1.5*iqr, souts=s.x[5]+3*iqr ) }
out.var<-calcQ(df$duration)
abline(h=611,col="red",lwd=2)
abline(h=917,col="magenta",lwd=2)

# Target numeric amb outliers greus: suprimir obs

#eliminamos las filas con NA's en las variables target (Duration & Y)
sel<-which(is.na(df$duration));sel
df<-df[-sel,]

sel<-which(is.na(df$y));sel
df<-df[-sel,]

# Missing values de las variables no target, y hacerle imputación

# age no consideramos ningún outlier

# job
dim(df$job)


# marital
# education
# default
# housing
# loan
# contact
# month
# day_of_week
# campaign
# pdays
# previous
# poutcome
# emp.var.rate
# cons.price.idx
# cons.conf.idx
# euribor3m
# nr.employed


# Eliminamos los outliers que pueden ser NA's

sel<-which(df$duration>3600);length(sel);sel
df<-df[-sel,]

# Outliers univariants podeu detectar-los i marcar-los com NA


# Errors: set to NA. Ex: Duration<=0
ll<-which(df$duration<=0);ll
df$duration[ll]<-NA

```

# Revisión de cada variable con summary y boxplots

```{r}

# age
summary(df$age)
hist(df$age,col="cyan",main="age - Histogram")
boxplot(df$age, labels=row.names(df))

# job
summary(df$job)

# marital
summary(df$marital)

# education
summary(df$education)

# default
summary(df$default)

# housing
summary(df$housing)

# loan
summary(df$loan)

# contact
summary(df$contact)

# month
summary(df$month)

# day_of_week
summary(df$day_of_week)

# duration
summary(df$duration)
hist(df$duration,col="cyan",main="duration - Histogram")
boxplot(df$duration, labels=row.names(df))

# campaign
summary(df$campaign)
sum(is.na(df$campaign))
hist(df$campaign,col="cyan",main="campaign - Histogram")
boxplot(df$campaign, labels=row.names(df))

# pdays
summary(df$pdays)
sum(is.na(df$pdays))
hist(df$pdays,col="cyan",main="pdays - Histogram")
boxplot(df$pdays, labels=row.names(df))

# previous
summary(df$previous)
sum(is.na(df$previous))
hist(df$previous,col="cyan",main="previous - Histogram")
boxplot(df$previous, labels=row.names(df))

# poutcome
summary(df$poutcome)

# emp.var.rate
summary(df$emp.var.rate)
sum(is.na(df$emp.var.rate))
hist(df$emp.var.rate,col="cyan",main="emp.var.rate - Histogram")
boxplot(df$emp.var.rate, labels=row.names(df))

# cons.price.idx
summary(df$cons.price.idx)
sum(is.na(df$cons.price.idx))
hist(df$cons.price.idx,col="cyan",main="cons.price.idx - Histogram")
boxplot(df$cons.price.idx, labels=row.names(df))

# cons.conf.idx
summary(df$cons.conf.idx)
sum(is.na(df$cons.conf.idx))
hist(df$cons.conf.idx,col="cyan",main="cons.conf.idx - Histogram")
boxplot(df$cons.conf.idx, labels=row.names(df))

# euribor3m
summary(df$euribor3m)
sum(is.na(df$euribor3m))
hist(df$euribor3m,col="cyan",main="euribor3m - Histogram")
boxplot(df$euribor3m, labels=row.names(df))

# nr.employed
summary(df$nr.employed)
sum(is.na(df$nr.employed))
hist(df$nr.employed,col="cyan",main="nr.employed - Histogram")
boxplot(df$nr.employed, labels=row.names(df))

# y
summary(df$y)
```

# crear lista de cuantitativos y cualitativos

```{r}
listaCualitativo<-list(df$job, df$marital, df$education, df$default, df$housing, df$loan, df$contact, df$month, df$day_of_week, df$poutcome, df$y)
names(listaCualitativo)<-c("job", "marital", "education", "default", "housing", "loan", "contact", "month", "day_of_week", "poutcome", "y")
listaCuantitativo<-list(df$age, df$duration, df$campaign, df$pdays, df$previous, df$emp.var.rate, df$cons.price.idx, df$cons.conf.idx, df$euribor3m, df$nr.employed)
names(listaCuantitativo)<-c("age", "duration", "campaign", "pdays", "previous", "emp.var.rate", "cons.price.idx", "cons.conf.idx", "euribor3m", "nr.employed")
```

# missing values de las variables target

# missing values 

# missing values de outliers


# Crear factores adicionales para cada variable cuantitativa
```{r}
# Para Age
qulist<-quantile(df$age,seq(0,1,0.25),na.rm=TRUE)

varaux<-factor(cut(df$age,breaks=qulist,include.lowest=T))
table(varaux)
tapply(df$age,varaux,median)
varaux<-factor(cut(df$age,breaks=c(18,30,40,50,92),include.lowest=T))
table(varaux)
tapply(df$age,varaux,median)

df$f.age<-factor(cut(df$age,breaks=c(18,30,40,50,92),include.lowest=T))

summary(df$f.age)
levels(df$f.age)<-paste0("f.age-",levels(df$f.age))

# Para duration
qulist<-quantile(df$duration,seq(0,1,0.25),na.rm=TRUE)

varaux<-factor(cut(df$duration,breaks=qulist,include.lowest=T))
table(varaux)
tapply(df$duration,varaux,median)
varaux<-factor(cut(df$duration,breaks=c(18,30,40,50,92),include.lowest=T))
table(varaux)
tapply(df$duration,varaux,median)

df$f.duration<-factor(cut(df$age,breaks=c(18,30,40,50,92),include.lowest=T))

summary(df$f.age)
levels(df$f.age)<-paste0("f.age-",levels(df$f.age))


```
